[build]
  publish = "dist"
  functions = "netlify/functions"

# Omdirigera /api/* till Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Hantera SPA-routing för Vue
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
